const proData =[
    {id: 1, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_01.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 2, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_02.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 3, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_03.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 4, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_04.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 5, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_05.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 6, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_06.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 7, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_07.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 8, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_08.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 9, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_09.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 10, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_10.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
    {id: 11, title: "Oupidatat non", sizes: "M/L/X/XL", price: '$250.00', coverImg: '/assets/img/shop_11.jpg', productImges: ['/assets/img/product_single_01.jpg','/assets/img/product_single_02.jpg','/assets/img/product_single_03.jpg','/assets/img/product_single_04.jpg','/assets/img/product_single_05.jpg','/assets/img/product_single_06.jpg','/assets/img/product_single_07.jpg','/assets/img/product_single_08.jpg','/assets/img/product_single_09.jpg','/assets/img/product_single_10.jpg']},
];
export default proData